experiment_name: ResNetFocal2
log_dir: ./experiments
epochs: 20
device: cuda:1
seed: 15

to_train: True
train:
  dataset:
    type: AgroVision2021Dataset
    params:
      csv_path: /datasets/rpartsey/agriculture_vision/csv/train_serialized.csv
      labels_path: /datasets/rpartsey/agriculture_vision/csv/labels_train.npy
      transforms:
        image:
          FromNumpy:
            params: null
          ToTorchFloat:
            params: null
        target:
          FromNumpy:
            params: null
          ToTorchFloat:
            params: null


      augmentations:
        type:
          - crop
          - flip
          - grid_mask
  loader:
    type: DataLoader
    params:
      batch_size: 15
      num_workers: 8
      shuffle: False
      sampler: DataSampler
  use_valid_masks: False


val:
  strip: 256
  dataset:
    type: AgroVision2021Dataset
    params:
      csv_path: /datasets/rpartsey/agriculture_vision/csv/val_serialized.csv
      labels_path: /datasets/rpartsey/agriculture_vision/csv/labels_train.npy
      transforms:
        image:
          FromNumpy:
            params: null
          ToTorchFloat:
            params: null
        target:
          FromNumpy:
            params: null
          ToTorchFloat:
            params: null
      augmentations: None
  loader:
    type: DataLoader
    params:
      batch_size: 12
      num_workers: 2
      shuffle: True
      sampler: null
  use_valid_masks: True

test:
  strip: 256
  save_to: /datasets/vey/agrovision/sub_2
  dataset:
    type: AgroVision2021DatasetTest
    params:
      csv_path: /datasets/rpartsey/agriculture_vision/csv/test_serialized.csv
      labels_path: /datasets/rpartsey/agriculture_vision/csv/labels_train.npy
      transforms:
        image:
          FromNumpy:
            params: null
          ToTorchFloat:
            params: null
      augmentations: None
  loader:
    type: DataLoader
    params:
      batch_size: 4
      num_workers: 2
      shuffle: False
      sampler: null
  use_valid_masks: True

model:
  type: Unet
  save: True
  load: /home/ocr/code/AgroVision2021/experiments/ResNetFocal/last_checkpoint.pt
  params:
    in_channels: 4
    out_channels: 7
    encoder_name: se_resnext101_32x4d
    decoder_channels:
      - 1024
      - 512
      - 256
      - 128
      - 64
loss:
  type: MultiLabelCrossEntropyMask
  params: null

metrics:
  IoU:
    params:
      threshold: 0.5

optim:
  type: Adam
  params:
    lr:
      - 0.00001
      - 0.000001
    weight_decay: 0.0005

stopper:
  params:
    patience: 12
