experiment_name: HARDSEGMENTATIONTest
log_dir: ./experiments
epochs: 10
device: cuda:0
seed: 20

to_train: False
parallel: True


train:
  strip: 256
  dataset:
    type: AgroVision2021DatasetNew
    params:
      csv_path: /datasets/vey/Agrovision2021/Agriculture-Vision-2021/csv/train_serialized.csv
      labels_path: /datasets/rpartsey/agriculture_vision/csv/labels_train.npy
      transforms:
        image:
          FromNumpy:
            params: null
          ToTorchFloat:
            params: null
        target:
          FromNumpy:
            params: null
          ToTorchFloat:
            params: null


      augmentations:
        type:
          - flip
          - grid_mask
          - strong
  loader:
    type: DataLoader
    params:
      batch_size: 8
      num_workers: 8
      shuffle: True
      sampler: null
  use_valid_masks: True


val:
  strip: 128
  dataset:
    type: AgroVision2021DatasetNew
    params:
      csv_path: /datasets/vey/Agrovision2021/Agriculture-Vision-2021/csv/val_serialized.csv
      labels_path: /datasets/rpartsey/agriculture_vision/csv/labels_train.npy
      transforms:
        image:
          FromNumpy:
            params: null
          ToTorchFloat:
            params: null
        target:
          FromNumpy:
            params: null
          ToTorchFloat:
            params: null
      augmentations: None
  loader:
    type: DataLoader
    params:
      batch_size: 8
      num_workers: 6
      shuffle: False
      sampler: null
  use_valid_masks: True

test:
  strip: 256
  save_to: /datasets/vey/agrovision/agro2021
  dataset:
    type: AgroVision2021DatasetTest
    params:
      csv_path: /datasets/vey/Agrovision2021/Agriculture-Vision-2021/csv/test_serialized.csv
      labels_path: /datasets/rpartsey/agriculture_vision/csv/labels_train.npy
      transforms:
        image:
          FromNumpy:
            params: null
          ToTorchFloat:
            params: null
      augmentations: None
  loader:
    type: DataLoader
    params:
      batch_size: 8
      num_workers: 12
      shuffle: False
      sampler: null
  use_valid_masks: True


model:
  type: Unet
  save: True
  load: /home/ocr/code/AgroVision2021/experiments/HARDSEGMENTATION/best_checkpoint.pt
  params:
    in_channels: 4
    out_channels: 9
    encoder_name: se_resnext101_32x4d
    decoder_channels:
      - 1024
      - 512
      - 256
      - 128
      - 64

loss:
  type: FixedMultiLabelCrossEntropyMask
  params: null

metrics:
  IoU:
    params:
      threshold: 0.5

optim:
  type: Adam
  params:
    lr:
      - 0.00001
      - 0.000001

stopper:
  params:
    patience: 12
