experiment_name: ACW_LossSGDUpdate6Class
log_dir: ./experiments
epochs: 10
device: cuda:1
seed: 10

to_train: True
train:

  dataset:
    type: AgroVision2021Dataset
    params:
      csv_path: /datasets/rpartsey/agriculture_vision/csv/train_serialized.csv
      labels_path: /datasets/rpartsey/agriculture_vision/csv/labels_train.npy
      transforms:
        image:
          FromNumpy:
            params: null
          ToTorchFloat:
            params: null
        target:
          FromNumpy:
            params: null
          ToTorchFloat:
            params: null


      augmentations: None

  loader:
    type: DataLoader
    params:
      batch_size: 7
      num_workers: 3
      shuffle: False
      sampler: DataSampler
  use_valid_masks: True


val:
  dataset:
    type: AgroVision2021Dataset
    params:
      csv_path: /datasets/rpartsey/agriculture_vision/csv/val_serialized.csv
      labels_path: /datasets/rpartsey/agriculture_vision/csv/labels_train.npy
      transforms:
        image:
          FromNumpy:
            params: null
          ToTorchFloat:
            params: null
        target:
          FromNumpy:
            params: null
          ToTorchFloat:
            params: null
      augmentations:
        type:
          - flip
  loader:
    type: DataLoader
    params:
      batch_size: 7
      num_workers: 2
      shuffle: False
      sampler: null
  use_valid_masks: True

test:
  save_to: /datasets/vey/agrovision/sub_1
  dataset:
    type: AgroVision2021DatasetTest
    params:
      csv_path: /datasets/rpartsey/agriculture_vision/csv/test_serialized.csv
      labels_path: /datasets/rpartsey/agriculture_vision/csv/labels_train.npy
      transforms:
        image:
          FromNumpy:
            params: null
          ToTorchFloat:
            params: null
      augmentations: None
  loader:
    type: DataLoader
    params:
      batch_size: 7
      num_workers: 2
      shuffle: False
      sampler: null
  use_valid_masks: True


model:
  type: Unet
  save: True
  load: /home/ocr/code/AgroVision2021/experiments/ACW_LossSGDUpdate63Class2/best_checkpoint.pt
  params:
    in_channels: 4
    out_channels: 6
    encoder_name: densenet161

loss:
  type: ACW_loss
  params: null

metrics:
  IoU:
    params:
      threshold: 0.5

optim:
  type: SGD
  params:
    lr:
      - 0.00001
      - 0.00005
      - 0.00001


stopper:
  params:
    patience: 12
