experiment_name: classification_agro4
log_dir: ./experiments
epochs: 30
device: cuda:0
seed: 1


train:

  dataset:
    type: AgroVision2021Dataset
    params:
      csv_path: /datasets/rpartsey/agriculture_vision/csv/train_serialized.csv
      labels_path: /datasets/rpartsey/agriculture_vision/csv/labels_train.npy
      transforms:
        image:
          FromNumpy:
            params: null
          ToTorchFloat:
            params: null
        target:
          FromNumpy:
            params: null
          ToTorchFloat:
            params: null


      augmentations:
        type:
          - flip
          - brightness

  loader:
    type: DataLoader
    params:
      batch_size: 4
      num_workers: 3
      shuffle: True
      sampler: null
  use_valid_masks: True


val:
  dataset:
    type: AgroVision2021Dataset
    params:
      csv_path: /datasets/rpartsey/agriculture_vision/csv/val_serialized.csv
      labels_path: /datasets/rpartsey/agriculture_vision/csv/labels_train.npy
      transforms:
        image:
          FromNumpy:
            params: null
          ToTorchFloat:
            params: null
        target:
          FromNumpy:
            params: null
          ToTorchFloat:
            params: null
      augmentations: None
  loader:
    type: DataLoader
    params:
      batch_size: 4
      num_workers: 2
      shuffle: False
      sampler: null
  use_valid_masks: True

test:
  save_to: /datasets/vey/agrovision/sub_1
  dataset:
    type: AgroVision2021DatasetTest
    params:
      csv_path: /datasets/rpartsey/agriculture_vision/csv/test_serialized.csv
      labels_path: /datasets/rpartsey/agriculture_vision/csv/labels_train.npy
      transforms:
        image:
          FromNumpy:
            params: null
          ToTorchFloat:
            params: null
      augmentations: None
  loader:
    type: DataLoader
    params:
      batch_size: 8
      num_workers: 2
      shuffle: False
      sampler: null
  use_valid_masks: True


model:
  type: SmpUnet
  save: True
  load: /home/ocr/code/AgroVision2021/experiments/classification_agro3/best_checkpoint.pt
  params:
    in_channels: 4
    out_channels: 6


loss:
  type: FixedMultiLabelCrossEntropyMask
  params: null

metrics:
  IoU:
    params:
      threshold: 0.5

optim:
  type: Adam
  params:
    lr:
      - 0.001
      - 0.0005
      - 0.0001
stopper:
  params:
    patience: 12
